#!/bin/bash 

if [ $# != 1 ];then
    echo -e "Usage: \n  $0 [name]\n\nPositional arguments:\n  name                  the name of independent space\n"
    exit
fi

base_path=$(dirname $(readlink -f $0)) # parent path for this script, that is $INDEPACE_HOME/.bin
p1=${base_path%/*} # path for $INDEPACE_HOME

if [ ! -L "~/.local/bin/"$1 -a ! -L $HOME'/.local/bin/'$1 ]; then
    ln -s $p1'/.bin/start_indepace' $HOME'/.local/bin/'$1
else 
    echo -n "Warnning: $HOME/.local/bin/$1 is exists, continue with backup? (y/n)"
    read op
    if [ "$op" == "y" ] || [ "$op" == "Y" ];then 
       eval "mv ~/.local/bin/"$1" ~/.local/bin/"$1".back"
       echo "backup "$1" to "$1".back and create new indepace"
       ln -f -s $p1'/.bin/start_indepace' $HOME'/.local/bin/'$1
    else 
       echo "installation cancel..."
       exit
    fi 
fi
# write $INDEPACE_USER to $p1/.bashrc
sed -i 's/^export INDEPACE_USER=.*$/export INDEPACE_USER='$1'/' $p1/.bashrc
